### ISSUE TITLE
poll.sh helper script doesn't accept polling time argument

### ISSUE THREAD

**Issue by tomsing1** [googlegenomics/pipelines-api-examples#28]
When called without arguments, the [poll.sh](https://github.com/googlegenomics/pipelines-api-examples/blob/master/tools/poll.sh) script returns 
`Usage: ./poll.sh OPERATION-ID <poll-interval-seconds>`, indicating that the user can specify the interval time as a second argument.

But it seems the usage check section (reproduced below) really only accepts a single argument, because of the `$# -ne 1` condition:
```
if [[ $# -ne 1 ]]; then
  echo "Usage: $0 OPERATION-ID <poll-interval-seconds>"
  exit 1
fi
```

**Comment by pgrosu** [comment]
Hi Thomas,

I would just submit a PR with the `if` line updated to the following, as the default would be 20 seconds for the poll interval:

```Bash
if [[ $# -lt 1 ]]; then
```
~p

**Comment by tomsing1** [comment]
Thanks, just submitted the pull request.

**Comment by pgrosu** [comment]
Great, thanks for contributing!  I will ping Matt on it, as he is one of the folks that can perform the merge.

**Comment by mbookman** [comment]
This was fixed by https://github.com/googlegenomics/pipelines-api-examples/pull/29
