### ISSUE TITLE
test_index.sh error with "curl" command

### ISSUE THREAD

**Issue by smrgit** [googlegenomics/pipelines-api-examples#49]
not sure if this is a script error or a Cloud Shell error, but when trying to use this script while following one of the tutorial examples (in Cloud Shell), the following command failed:
```
curl -O ftp://ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/pilot3_exon_targetted_GRCh37_bams/data/NA06986/alignment/NA06986.chromMT.ILLUMINA.bwa.CEU.exon_targetted.20100311.bam
```
the problem may be the combination of ``curl`` and an ``ftp`` url -- modifying the script or including some comments about other options would be helpful -- eg the file can also be obtained from
```
http://storage.googleapis.com/genomics-public-data/ftp-trace.ncbi.nih.gov/1000genomes/ftp/technical/pilot3_exon_targetted_GRCh37_bams/data/NA06986/alignment/NA06986.chromMT.ILLUMINA.bwa.CEU.exon_targetted.20100311.bam
```

**Comment by mbookman** [comment]
Fixed by https://github.com/googlegenomics/pipelines-api-examples/pull/64
