### ISSUE TITLE
Enable multiple inputs JSONs

### ISSUE THREAD

**Issue by vdauwera** [googlegenomics/pipelines-api-examples#53]
Cromwell now supports providing multiple JSON files of inputs, which provides significant convenience for managing inputs. 

For example, for a given WDL, I can feed Cromwell one JSON file with input data files (where inputs will typically change for every run of the pipeline), one JSON with analysis parameters (typically the same between runs), and one with performance-related parameters (eg Java heap size for each task) that amount to a sort of configuration, which I might want to swap out depending on the urgency of a project. 

This would provide great value if it were supported by wdl_runner.

**Comment by mbookman** [comment]
Closing this issue here as wdl_runner is no longer part of this repo. It is now part of the [openwdl](https://github.com/openwdl/wdl) repo.
