### ISSUE TITLE
Update Cromwell Version

### ISSUE THREAD

**Issue by ruchim** [googlegenomics/pipelines-api-examples#58]
Cromwell recently had a new release and I would like to update the Cromwell version inside the wdl_runner to v26. I have an updated local docker image of the wdl_runner utilizing Cromwell v26, but not the permissions to push it to an appropriate repo. What's the best way to proceed?

**Comment by mbookman** [comment]
wdl_runner has been updated to Cromwell 27 with https://github.com/googlegenomics/pipelines-api-examples/pull/66.
