### ISSUE TITLE
Updates to Jes template conf for Cromwell v24

### ISSUE THREAD

**Issue by ruchim** [googlegenomics/pipelines-api-examples#60]
There are some config changes required for using Cromwell v24.

The current google stanza in the Jes template looks like:
`
google {
  applicationName = "cromwell"
  cromwellAuthenticationScheme = "application_default"
}
`
but it needs to be:
`
google {
  application-name = "cromwell"
  auths = [
    {
      name = "application-default"
      scheme = "application_default"
    }
  ]
}
`

There's also the introduction of an additional required stanza:
`
engine {
  filesystems {
    gcs {
      auth = "application-default"
    }
  }
}
`

**Comment by vdauwera** [comment]
@mbookman

**Comment by mbookman** [comment]
Cromwell has been updated to version 27 with https://github.com/googlegenomics/pipelines-api-examples/pull/66.
