### ISSUE TITLE
link in section (3) of README is broken

### ISSUE THREAD

**Issue by smrgit** [googlegenomics/pipelines-api-examples#68]
the link to the monitor_wdl_pipelines.sh in the README is broken
![image](https://user-images.githubusercontent.com/3067449/28232648-bfe08884-68a6-11e7-8583-420b4f550706.png)

**Comment by mbookman** [comment]
Thanks Sheila. "pipeline" should be singular in the file name: monitor_wdl_pipeline.sh

**Comment by smrgit** [comment]
still broken -- could someone fix this typo please?  thx!

**Comment by mbookman** [comment]
Hi Sheila,

The Broad has taken over the wdl_runner.
We will update docs soon to reference it:

https://github.com/openwdl/wdl/tree/develop/runners/cromwell_on_google

**Comment by mbookman** [comment]
The link has been corrected on the openwdl site with https://github.com/openwdl/wdl/pull/145.
